### ISSUE TITLE
meshScalar value limit

### ISSUE THREAD

**Issue by chetu3319** [ScatterCo/Depthkit.js#2]
Proper value check using `floor()` or `step()` functions to have only integer value. -> https://github.com/ScatterCo/Depthkit.js/blob/b1fc3a10bfb606f2d47129fa6dab5e37251a949a/src/depthkit.js#L48-L49

Also setting `meshScalar = 0;` breaks the whole code fundamentally it will be `NaN`.

**Comment by tim-depthkit** [comment]
Updated to support values 0-3 inclusive, clamps input to this range, and uses floor() to handle floating point input.
0 - 1 vertex per depth pixel
1 - 1 vertex per every 2 depth pixels
2 - 1 vertex per every 4 depth pixels
3 - 1 vertex per every 8 depth pixels
