### ISSUE TITLE
Changing the pivot to the centre of the bounding box. 

### ISSUE THREAD

**Issue by chetu3319** [ScatterCo/Depthkit.js#3]
Currently, the anchor point is at the corner of the bounding box.
This makes the normal transform operations like `translate`, `rotate`, and `scale` as they occur w.r.t the pivot and not w.r.t to the center of the bounding box.

**Comment by tim-depthkit** [comment]
Updated pivot point to be the center of the depth camera frustum bounded by near and far clipping planes
